export interface RecallRankingSqlSource {
  readonly selectRankedClaims: string;
}

const contestedExpression = [
  "CASE WHEN source_claim.relation IN ('uses','rejects') THEN EXISTS (",
  "  SELECT 1",
  "  FROM claims AS opposite_claim",
  "  JOIN temp.recall_claim_agg AS opposite_aggregate",
  "    ON opposite_aggregate.claim_id = opposite_claim.id",
  "  WHERE opposite_claim.scope_key = source_claim.scope_key",
  "    AND opposite_claim.subject_id = source_claim.subject_id",
  "    AND opposite_claim.object_id IS source_claim.object_id",
  "    AND opposite_claim.object_value IS source_claim.object_value",
  "    AND opposite_claim.relation = CASE source_claim.relation",
  "      WHEN 'uses' THEN 'rejects'",
  "      WHEN 'rejects' THEN 'uses'",
  "    END",
  ") ELSE 0 END",
].join("\n");

const selectRankedClaims = [
  "WITH requested_reached AS (",
  "  SELECT",
  "    json_extract(requested.value, '$.claimId') AS requested_claim_id,",
  "    json_extract(requested.value, '$.depth') AS requested_depth",
  "  FROM json_each(:reached_json) AS requested",
  "),",
  "claim_facts AS (",
  "  SELECT",
  "    source_claim.id AS recall_ranking_claim_id,",
  "    source_claim.scope_key AS recall_ranking_claim_scope_key,",
  "    source_claim.state AS recall_ranking_claim_state,",
  "    source_claim.origin_seq AS recall_ranking_origin_seq,",
  "    source_claim.relation AS recall_ranking_relation,",
  "    source_claim.object_value AS recall_ranking_object_value,",
  "    requested_reached.requested_depth AS recall_ranking_depth,",
  "    valid_claim.support_count AS recall_ranking_support_count,",
  "    valid_claim.strongest_rank AS recall_ranking_strongest_rank,",
  "    valid_claim.last_seen_at AS recall_ranking_last_seen_at,",
  "    valid_claim.relation_label AS recall_ranking_relation_label,",
  "    subject_entity.id AS recall_ranking_subject_id,",
  "    subject_entity.name AS recall_ranking_subject_name,",
  "    subject_entity.scope_key AS recall_ranking_subject_scope_key,",
  "    subject_entity.merged_into AS recall_ranking_subject_merged_into,",
  "    object_entity.id AS recall_ranking_object_id,",
  "    object_entity.name AS recall_ranking_object_name,",
  "    object_entity.scope_key AS recall_ranking_object_scope_key,",
  "    object_entity.merged_into AS recall_ranking_object_merged_into,",
  `    ${contestedExpression} AS recall_ranking_contested,`,
  "    CASE WHEN valid_claim.last_seen_at BETWEEN (:now - 2592000) AND :now",
  "      THEN 1 ELSE 0 END AS recall_ranking_recent",
  "  FROM requested_reached",
  "  JOIN temp.recall_claim_agg AS valid_claim",
  "    ON valid_claim.claim_id = requested_reached.requested_claim_id",
  "  JOIN claims AS source_claim ON source_claim.id = valid_claim.claim_id",
  "  JOIN entities AS subject_entity ON subject_entity.id = source_claim.subject_id",
  "  LEFT JOIN entities AS object_entity ON object_entity.id = source_claim.object_id",
  "  WHERE source_claim.scope_key = :scope_key",
  "),",
  "scored_claims AS (",
  "  SELECT",
  "    claim_facts.*,",
  "    (-2 * claim_facts.recall_ranking_depth)",
  "      + CASE claim_facts.recall_ranking_strongest_rank",
  "          WHEN 3 THEN 6",
  "          WHEN 2 THEN 4",
  "          ELSE 1",
  "        END",
  "      + MIN(claim_facts.recall_ranking_support_count, 4)",
  "      + (2 * claim_facts.recall_ranking_recent)",
  "      - (3 * claim_facts.recall_ranking_contested)",
  "      AS recall_ranking_score",
  "  FROM claim_facts",
  ")",
  "SELECT",
  "  scored_claims.recall_ranking_claim_id AS recall_ranking_claim_id,",
  "  scored_claims.recall_ranking_claim_scope_key AS recall_ranking_claim_scope_key,",
  "  scored_claims.recall_ranking_claim_state AS recall_ranking_claim_state,",
  "  scored_claims.recall_ranking_origin_seq AS recall_ranking_origin_seq,",
  "  scored_claims.recall_ranking_relation AS recall_ranking_relation,",
  "  scored_claims.recall_ranking_object_value AS recall_ranking_object_value,",
  "  scored_claims.recall_ranking_depth AS recall_ranking_depth,",
  "  scored_claims.recall_ranking_support_count AS recall_ranking_support_count,",
  "  scored_claims.recall_ranking_strongest_rank AS recall_ranking_strongest_rank,",
  "  scored_claims.recall_ranking_last_seen_at AS recall_ranking_last_seen_at,",
  "  scored_claims.recall_ranking_relation_label AS recall_ranking_relation_label,",
  "  scored_claims.recall_ranking_subject_id AS recall_ranking_subject_id,",
  "  scored_claims.recall_ranking_subject_name AS recall_ranking_subject_name,",
  "  scored_claims.recall_ranking_subject_scope_key AS recall_ranking_subject_scope_key,",
  "  scored_claims.recall_ranking_subject_merged_into AS recall_ranking_subject_merged_into,",
  "  scored_claims.recall_ranking_object_id AS recall_ranking_object_id,",
  "  scored_claims.recall_ranking_object_name AS recall_ranking_object_name,",
  "  scored_claims.recall_ranking_object_scope_key AS recall_ranking_object_scope_key,",
  "  scored_claims.recall_ranking_object_merged_into AS recall_ranking_object_merged_into,",
  "  scored_claims.recall_ranking_contested AS recall_ranking_contested,",
  "  scored_claims.recall_ranking_recent AS recall_ranking_recent,",
  "  scored_claims.recall_ranking_score AS recall_ranking_score,",
  "  COUNT(*) OVER () AS recall_ranking_total_count",
  "FROM scored_claims",
  "ORDER BY",
  "  scored_claims.recall_ranking_score DESC,",
  "  scored_claims.recall_ranking_depth ASC,",
  "  scored_claims.recall_ranking_strongest_rank DESC,",
  "  scored_claims.recall_ranking_support_count DESC,",
  "  scored_claims.recall_ranking_last_seen_at DESC,",
  "  scored_claims.recall_ranking_origin_seq ASC,",
  "  CAST(SUBSTR(scored_claims.recall_ranking_claim_id, INSTR(scored_claims.recall_ranking_claim_id, '.') + 1) AS INTEGER) ASC,",
  "  scored_claims.recall_ranking_claim_id COLLATE BINARY ASC",
  "LIMIT :probe_limit",
].join("\n");

/**
 * RCL-006 ranks only caller-validated reached IDs inside the active recall
 * snapshot. Runtime values remain named bindings and the TEMP aggregate is the
 * sole source of validity, support, labels, and opposite-claim eligibility.
 */
export const RECALL_RANKING_SQL_SOURCE: RecallRankingSqlSource = Object.freeze({
  selectRankedClaims,
});
