export interface RecallFtsSqlSource {
  readonly selectCandidateStatements: string;
  readonly selectCandidateSupports: string;
  readonly matchCandidatePhrase: string;
}

const validCandidateSupportExists = [
  "EXISTS (",
  "  SELECT 1",
  "  FROM claim_support AS eligible_support",
  "  JOIN temp.recall_claim_agg AS eligible_aggregate",
  "    ON eligible_aggregate.claim_id = eligible_support.claim_id",
  "  JOIN claims AS eligible_claim",
  "    ON eligible_claim.id = eligible_support.claim_id",
  "  WHERE eligible_support.event_id = candidate_journal.id",
  "    AND eligible_support.live = 1",
  "    AND (eligible_support.expires_at IS NULL",
  "         OR eligible_support.expires_at > :now)",
  "    AND eligible_claim.scope_key = :scope_key",
  "    AND eligible_support.draft_index >= 0",
  "    AND eligible_support.draft_index <",
  "        json_array_length(candidate_journal.body, '$.parsed')",
  ")",
].join("\n");

const malformedCandidateSupportExists = [
  "EXISTS (",
  "  SELECT 1",
  "  FROM claim_support AS malformed_support",
  "  JOIN temp.recall_claim_agg AS malformed_aggregate",
  "    ON malformed_aggregate.claim_id = malformed_support.claim_id",
  "  JOIN claims AS malformed_claim",
  "    ON malformed_claim.id = malformed_support.claim_id",
  "  WHERE malformed_support.event_id = candidate_journal.id",
  "    AND malformed_support.live = 1",
  "    AND (malformed_support.expires_at IS NULL",
  "         OR malformed_support.expires_at > :now)",
  "    AND malformed_claim.scope_key = :scope_key",
  "    AND json_type(candidate_journal.body, '$.parsed') = 'array'",
  "    AND (malformed_support.draft_index < 0",
  "         OR malformed_support.draft_index >=",
  "            json_array_length(candidate_journal.body, '$.parsed'))",
  ")",
].join("\n");

const validGraphDuplicateExists = [
  "EXISTS (",
  "  SELECT 1",
  "  FROM journal AS duplicate_journal",
  "  JOIN statements AS duplicate_statement",
  "    ON duplicate_statement.event_id = duplicate_journal.id",
  "  JOIN claim_support AS duplicate_support",
  "    ON duplicate_support.event_id = duplicate_journal.id",
  "  JOIN temp.recall_claim_agg AS duplicate_aggregate",
  "    ON duplicate_aggregate.claim_id = duplicate_support.claim_id",
  "  JOIN claims AS duplicate_claim",
  "    ON duplicate_claim.id = duplicate_support.claim_id",
  "  WHERE duplicate_journal.kind = 'statement'",
  "    AND duplicate_journal.scope_key = :scope_key",
  "    AND duplicate_statement.scope_key = :scope_key",
  "    AND duplicate_claim.scope_key = :scope_key",
  "    AND duplicate_statement.state = 'live'",
  "    AND (duplicate_statement.expires_at IS NULL",
  "         OR duplicate_statement.expires_at > :now)",
  "    AND duplicate_support.live = 1",
  "    AND (duplicate_support.expires_at IS NULL",
  "         OR duplicate_support.expires_at > :now)",
  "    AND json_type(duplicate_journal.body, '$.raw_text') = 'text'",
  "    AND json_extract(duplicate_journal.body, '$.raw_text') =",
  "        json_extract(candidate_journal.body, '$.raw_text')",
  "    AND json_type(duplicate_journal.body, '$.parsed') = 'array'",
  "    AND json_array_length(duplicate_journal.body, '$.parsed') > 0",
  "    AND duplicate_support.draft_index >= 0",
  "    AND duplicate_support.draft_index <",
  "        json_array_length(duplicate_journal.body, '$.parsed')",
  ")",
].join("\n");

const selectCandidateStatements = [
  "SELECT",
  "  candidate_journal.id AS recall_fts_event_id,",
  "  candidate_journal.seq AS recall_fts_statement_seq,",
  "  bm25(journal_fts) AS recall_fts_rank,",
  "  json_type(candidate_journal.body, '$.raw_text') AS recall_fts_raw_text_type,",
  "  json_extract(candidate_journal.body, '$.raw_text') AS recall_fts_raw_text,",
  "  json_type(candidate_journal.body, '$.parsed') AS recall_fts_parsed_type,",
  "  json_array_length(candidate_journal.body, '$.parsed') AS recall_fts_parsed_count,",
  "  candidate_journal.scope_key AS recall_fts_journal_scope_key,",
  "  candidate_journal.created_at AS recall_fts_recorded_at,",
  "  candidate_statement.scope_key AS recall_fts_statement_scope_key,",
  "  candidate_statement.state AS recall_fts_statement_state,",
  "  candidate_statement.created_at AS recall_fts_created_at,",
  "  candidate_statement.provenance AS recall_fts_provenance,",
  "  candidate_statement.expires_at AS recall_fts_statement_expires_at,",
  `  ${validGraphDuplicateExists} AS recall_fts_has_valid_graph_duplicate`,
  "FROM journal_fts",
  "JOIN journal AS candidate_journal",
  "  ON candidate_journal.seq = journal_fts.rowid",
  "JOIN statements AS candidate_statement",
  "  ON candidate_statement.event_id = candidate_journal.id",
  "WHERE journal_fts MATCH :fts_query",
  "  AND candidate_journal.kind = 'statement'",
  "  AND candidate_journal.scope_key = :scope_key",
  "  AND candidate_statement.scope_key = :scope_key",
  "  AND candidate_statement.state = 'live'",
  "  AND (candidate_statement.expires_at IS NULL",
  "       OR candidate_statement.expires_at > :now)",
  "  AND (",
  "    json_type(candidate_journal.body, '$.raw_text') IS NOT 'text'",
  "    OR json_type(candidate_journal.body, '$.parsed') IS NOT 'array'",
  "    OR json_array_length(candidate_journal.body, '$.parsed') > 100",
  `    OR ${validCandidateSupportExists}`,
  `    OR ${malformedCandidateSupportExists}`,
  "    OR (",
  "      json_array_length(candidate_journal.body, '$.parsed') = 0",
  `      AND NOT ${validGraphDuplicateExists}`,
  "    )",
  "  )",
  "ORDER BY recall_fts_rank ASC, candidate_journal.seq DESC",
  "LIMIT 21",
].join("\n");

const selectCandidateSupports = [
  "SELECT",
  "  candidate_support.event_id AS recall_fts_support_event_id,",
  "  candidate_support.draft_index AS recall_fts_support_draft_index,",
  "  candidate_support.live AS recall_fts_support_live,",
  "  candidate_support.expires_at AS recall_fts_support_expires_at,",
  "  candidate_claim.id AS recall_fts_claim_id,",
  "  candidate_claim.scope_key AS recall_fts_claim_scope_key,",
  "  candidate_claim.state AS recall_fts_claim_state,",
  "  candidate_claim.origin_seq AS recall_fts_claim_origin_seq,",
  "  candidate_claim.subject_id AS recall_fts_subject_id,",
  "  subject_entity.scope_key AS recall_fts_subject_scope_key,",
  "  subject_entity.merged_into AS recall_fts_subject_merged_into,",
  "  candidate_claim.object_id AS recall_fts_object_id,",
  "  object_entity.scope_key AS recall_fts_object_scope_key,",
  "  object_entity.merged_into AS recall_fts_object_merged_into,",
  "  CASE WHEN candidate_claim.object_value IS NULL THEN 0 ELSE 1 END",
  "    AS recall_fts_has_object_value",
  "FROM claim_support AS candidate_support",
  "JOIN temp.recall_claim_agg AS valid_claim",
  "  ON valid_claim.claim_id = candidate_support.claim_id",
  "JOIN claims AS candidate_claim",
  "  ON candidate_claim.id = candidate_support.claim_id",
  "JOIN entities AS subject_entity",
  "  ON subject_entity.id = candidate_claim.subject_id",
  "LEFT JOIN entities AS object_entity",
  "  ON object_entity.id = candidate_claim.object_id",
  "WHERE candidate_support.event_id = :event_id",
  "  AND candidate_support.live = 1",
  "  AND (candidate_support.expires_at IS NULL",
  "       OR candidate_support.expires_at > :now)",
  "  AND candidate_claim.scope_key = :scope_key",
  "ORDER BY candidate_support.draft_index ASC,",
  "         candidate_claim.origin_seq ASC,",
  "         candidate_claim.id ASC",
].join("\n");

const matchCandidatePhrase = [
  "SELECT EXISTS (",
  "  SELECT 1",
  "  FROM journal_fts",
  "  WHERE journal_fts.rowid = CAST(:statement_seq AS INTEGER)",
  "    AND journal_fts MATCH :fts_phrase",
  ") AS recall_fts_phrase_matches",
].join("\n");

export const RECALL_FTS_SQL_SOURCE: RecallFtsSqlSource = Object.freeze({
  selectCandidateStatements,
  selectCandidateSupports,
  matchCandidatePhrase,
});
